// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dto.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `seed32`

/// Convert `amount_cents` from `from_currency` to `to_currency` at `rate_micro`
/// (target units per source unit, ×1e6). Integer-safe; the money math lives in
/// Rust so the shell never duplicates it (#3).
Future<PlatformInt64> convertCurrency({
  required PlatformInt64 amountCents,
  required PlatformInt64 rateMicro,
  required String fromCurrency,
  required String toCurrency,
}) => RustLib.instance.api.crateApiConvertCurrency(
  amountCents: amountCents,
  rateMicro: rateMicro,
  fromCurrency: fromCurrency,
  toCurrency: toCurrency,
);

/// The number of minor units (decimal places) for a currency code — for
/// formatting amounts on the shell side (#3).
Future<int> currencyMinorUnits({required String code}) =>
    RustLib.instance.api.crateApiCurrencyMinorUnits(code: code);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Engine>>
abstract class Engine implements RustOpaqueInterface {
  Future<List<ActivityEntryDto>> activity();

  Future<String> addExpense({required ExpenseInput input});

  Future<void> addMember({required String groupId, required String userId});

  Future<String> addPerson({required String name});

  Future<String> createGroup({
    required String name,
    required List<String> memberIds,
    required String currency,
  });

  Future<void> deleteExpense({required String expenseId});

  Future<void> deleteSettlement({required String settlementId});

  /// Replace an expense with a new version. `input.group_id` is ignored (an
  /// expense cannot change groups).
  Future<void> editExpense({
    required String expenseId,
    required ExpenseInput input,
  });

  Future<FriendDetailDto?> friendDetail({required String userId});

  Future<List<FriendBalanceDto>> friends();

  Future<GroupDetailDto?> groupDetail({required String groupId});

  Future<List<GroupSummaryDto>> groups();

  Future<void> lockExpense({required String expenseId});

  Future<String?> myName();

  Future<String> myUserId();

  /// Open (or create) the engine over a redb database at `db_path`.
  ///
  /// `identity_seed` (32 bytes) is the local user's signing key and `db_key`
  /// (32 bytes) encrypts the op-log at rest (#22). The platform supplies both
  /// from secure storage / a keystore (#6/#16) — they are never derived from,
  /// or stored next to, the database.
  static Future<Engine> open({
    required String dbPath,
    required List<int> identitySeed,
    required List<int> dbKey,
    required BigInt site,
  }) => RustLib.instance.api.crateApiEngineOpen(
    dbPath: dbPath,
    identitySeed: identitySeed,
    dbKey: dbKey,
    site: site,
  );

  /// The local user's overall net across all expenses/settlements, including
  /// non-group ones (#31). Positive = owed to you.
  Future<PlatformInt64> overallNetCents();

  /// Publish a draft expense so it counts toward balances (#15).
  Future<void> publishExpense({required String expenseId});

  /// Record a non-group (friend-to-friend) payment (#31).
  Future<String> recordNonGroupSettlement({
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  });

  Future<String> recordSettlement({
    required String groupId,
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  });

  Future<void> removeMember({required String groupId, required String userId});

  Future<void> renameGroup({required String groupId, required String name});

  /// Close a group's accounting period (#15): expenses dated at or before
  /// `until_ms` become uneditable. Pass `0` to reopen.
  Future<void> setClosedPeriod({
    required String groupId,
    required PlatformInt64 untilMs,
  });

  Future<void> setGroupCurrency({
    required String groupId,
    required String currency,
  });

  Future<void> setMyName({required String name});

  Future<void> unlockExpense({required String expenseId});
}
