// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dto.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hex32`, `lock`, `open_with`, `parse_hex32`, `seed32`

/// Convert `amount_cents` from `from_currency` to `to_currency` at `rate_micro`
/// (target units per source unit, ×1e6). Integer-safe; the money math lives in
/// Rust so the shell never duplicates it (#3).
Future<PlatformInt64> convertCurrency({
  required PlatformInt64 amountCents,
  required PlatformInt64 rateMicro,
  required String fromCurrency,
  required String toCurrency,
}) => RustLib.instance.api.crateApiConvertCurrency(
  amountCents: amountCents,
  rateMicro: rateMicro,
  fromCurrency: fromCurrency,
  toCurrency: toCurrency,
);

/// The number of minor units (decimal places) for a currency code — for
/// formatting amounts on the shell side (#3).
Future<int> currencyMinorUnits({required String code}) =>
    RustLib.instance.api.crateApiCurrencyMinorUnits(code: code);

/// The BIP39 recovery phrase for a 32-byte identity seed (#34).
Future<String> recoveryPhrase({required List<int> identitySeed}) =>
    RustLib.instance.api.crateApiRecoveryPhrase(identitySeed: identitySeed);

/// Re-derive the 32-byte identity seed from a recovery phrase (#34).
Future<Uint8List> seedFromRecoveryPhrase({required String phrase}) =>
    RustLib.instance.api.crateApiSeedFromRecoveryPhrase(phrase: phrase);

/// Seal a 32-byte root seed under the app-lock `passphrase` for at-rest storage
/// on the primary device (#34/ADR-0005). Returns the opaque sealed blob.
Future<Uint8List> sealRootSeed({
  required String passphrase,
  required List<int> seed,
}) => RustLib.instance.api.crateApiSealRootSeed(
  passphrase: passphrase,
  seed: seed,
);

/// Open a [`seal_root_seed`] blob. `None` if the passphrase is wrong or the blob
/// was tampered with (#34).
Future<Uint8List?> openRootSeed({
  required String passphrase,
  required List<int> blob,
}) => RustLib.instance.api.crateApiOpenRootSeed(
  passphrase: passphrase,
  blob: blob,
);

/// Decode and verify a shared invite blob (#7). Returns the inviter, context,
/// and whether it is currently valid (signature ok and not expired as of
/// `now_ms`, Unix ms); `None` if the blob is malformed.
Future<InviteDto?> verifyInvite({
  required List<int> invite,
  required BigInt nowMs,
}) => RustLib.instance.api.crateApiVerifyInvite(invite: invite, nowMs: nowMs);

/// The device-enrolment short authentication string both devices compare to
/// defeat a man-in-the-middle (#35). All keys are 32-byte hex; `challenge` is
/// the 32-byte one-time pairing nonce.
Future<String> pairingShortAuthString({
  required String identityHex,
  required String primaryDeviceHex,
  required String newDeviceHex,
  required List<int> challenge,
}) => RustLib.instance.api.crateApiPairingShortAuthString(
  identityHex: identityHex,
  primaryDeviceHex: primaryDeviceHex,
  newDeviceHex: newDeviceHex,
  challenge: challenge,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Engine>>
abstract class Engine implements RustOpaqueInterface {
  Future<List<ActivityEntryDto>> activity();

  Future<String> addExpense({required ExpenseInput input});

  /// Declare friendship toward another identity (#7). Confirmed once mutual.
  Future<void> addFriend({required String userId});

  Future<void> addMember({required String groupId, required String userId});

  Future<String> addPerson({required String name});

  /// Authorize another device (hex public key) to act for this identity.
  Future<void> authorizeDevice({
    required String deviceHex,
    required BigInt site,
  });

  /// Claim a placeholder person as the local identity (#8): their history
  /// resolves to you with no balance change.
  Future<void> claimPerson({required String placeholder});

  /// The local user's confirmed (mutual) friends (#7).
  Future<List<String>> confirmedFriends();

  /// A signed friend invite for the local identity, valid until `expiry_ms`
  /// (Unix ms). Encodes to an opaque blob for a link/QR (#7). Needs the root
  /// unlocked (#34).
  Future<Uint8List> createFriendInvite({required BigInt expiryMs});

  Future<String> createGroup({
    required String name,
    required List<String> memberIds,
    required String currency,
  });

  /// A signed invite to join `group_id`, valid until `expiry_ms` (#7).
  Future<Uint8List> createGroupInvite({
    required String groupId,
    required BigInt expiryMs,
  });

  Future<void> deleteExpense({required String expenseId});

  Future<void> deleteSettlement({required String settlementId});

  /// Replace an expense with a new version. `input.group_id`/`draft` are
  /// ignored (an expense cannot change groups, and edit preserves draft state).
  Future<void> editExpense({
    required String expenseId,
    required ExpenseInput input,
  });

  Future<FriendDetailDto?> friendDetail({required String userId});

  Future<List<FriendBalanceDto>> friends();

  Future<GroupDetailDto?> groupDetail({required String groupId});

  Future<List<GroupSummaryDto>> groups();

  /// The identity (root) public key as hex — persist it after the first
  /// (full) open so later launches can `open_device_only` (#34).
  Future<String> identityPublic();

  Future<bool> isRootUnlocked();

  Future<List<DeviceViewDto>> listDevices();

  Future<void> lockExpense({required String expenseId});

  /// Re-seal the root after a privileged action.
  Future<void> lockRoot();

  /// Merge two ids that are the same person (#8), keeping `keep` as canonical.
  Future<void> mergePeople({required String duplicate, required String keep});

  /// The local user's X25519 agreement public key as hex (#6/#14). `None`
  /// before a profile has published it (locked, never-named identity).
  Future<String?> myAgreementPublic();

  /// This device's public key (hex) — share it to enrol from another device.
  Future<String> myDevicePublic();

  Future<String?> myName();

  Future<String> myUserId();

  /// Open (or create) the engine over a redb database at `db_path`.
  ///
  /// `identity_seed` (32 bytes) is the local user's signing key and `db_key`
  /// (32 bytes) encrypts the op-log at rest (#22). The platform supplies both
  /// from secure storage / a keystore (#6/#16) — they are never derived from,
  /// or stored next to, the database.
  static Future<Engine> open({
    required String dbPath,
    required List<int> identitySeed,
    required List<int> deviceSeed,
    required List<int> dbKey,
    required BigInt site,
  }) => RustLib.instance.api.crateApiEngineOpen(
    dbPath: dbPath,
    identitySeed: identitySeed,
    deviceSeed: deviceSeed,
    dbKey: dbKey,
    site: site,
  );

  /// Open for daily use with the root **locked** (#34): the device key signs
  /// ops, the public identity is known, and privileged actions (enrol/revoke)
  /// require [`unlock_root`](Engine::unlock_root). The device must already be
  /// enrolled — i.e. this identity ran a full `open` on this device before.
  /// `identity_public` is the 32-byte identity (root) public key.
  static Future<Engine> openDeviceOnly({
    required String dbPath,
    required List<int> identityPublic,
    required List<int> deviceSeed,
    required List<int> dbKey,
    required BigInt site,
  }) => RustLib.instance.api.crateApiEngineOpenDeviceOnly(
    dbPath: dbPath,
    identityPublic: identityPublic,
    deviceSeed: deviceSeed,
    dbKey: dbKey,
    site: site,
  );

  /// The local user's overall net across all expenses/settlements, including
  /// non-group ones (#31). Positive = owed to you.
  Future<PlatformInt64> overallNetCents();

  /// Publish a draft expense so it counts toward balances (#15).
  Future<void> publishExpense({required String expenseId});

  /// Record a non-group (friend-to-friend) payment (#31).
  Future<String> recordNonGroupSettlement({
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  });

  Future<String> recordSettlement({
    required String groupId,
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  });

  Future<void> removeMember({required String groupId, required String userId});

  Future<void> renameGroup({required String groupId, required String name});

  /// Revoke a device (hex public key).
  Future<void> revokeDevice({required String deviceHex});

  /// Close a group's accounting period (#15): expenses dated at or before
  /// `until_ms` become uneditable. Pass `0` to reopen.
  Future<void> setClosedPeriod({
    required String groupId,
    required PlatformInt64 untilMs,
  });

  Future<void> setGroupCurrency({
    required String groupId,
    required String currency,
  });

  Future<void> setMyName({required String name});

  Future<void> unlockExpense({required String expenseId});

  /// Unlock the root from its seed (after the app lock decrypts the vault) so
  /// device enrol/revoke can be signed; errors if the seed is for another
  /// identity (#34).
  Future<void> unlockRoot({required List<int> identitySeed});
}
