// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dto.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `seed32`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Engine>>
abstract class Engine implements RustOpaqueInterface {
  Future<List<ActivityEntryDto>> activity();

  Future<String> addExpense({required ExpenseInput input});

  Future<void> addMember({required String groupId, required String userId});

  Future<String> addPerson({required String name});

  Future<String> createGroup({
    required String name,
    required List<String> memberIds,
  });

  Future<void> deleteExpense({required String expenseId});

  Future<void> deleteSettlement({required String settlementId});

  /// Replace an expense with a new version. `input.group_id` is ignored (an
  /// expense cannot change groups).
  Future<void> editExpense({
    required String expenseId,
    required ExpenseInput input,
  });

  Future<FriendDetailDto?> friendDetail({required String userId});

  Future<List<FriendBalanceDto>> friends();

  Future<GroupDetailDto?> groupDetail({required String groupId});

  Future<List<GroupSummaryDto>> groups();

  Future<void> lockExpense({required String expenseId});

  Future<String?> myName();

  Future<String> myUserId();

  /// Open (or create) the engine over a redb database at `db_path`, using the
  /// 32-byte `identity_seed` as the local user's signing key (the platform
  /// loads/persists this from secure storage — #16).
  static Future<Engine> open({
    required String dbPath,
    required List<int> identitySeed,
    required BigInt site,
  }) => RustLib.instance.api.crateApiEngineOpen(
    dbPath: dbPath,
    identitySeed: identitySeed,
    site: site,
  );

  Future<String> recordSettlement({
    required String groupId,
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  });

  Future<void> removeMember({required String groupId, required String userId});

  Future<void> renameGroup({required String groupId, required String name});

  Future<void> setMyName({required String name});

  Future<void> unlockExpense({required String expenseId});
}
