// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

/// One entry in the activity feed. `kind` is a coarse tag for icon selection:
/// `group`, `expense`, `edit`, `delete`, `settlement`, `person`.
class ActivityEntryDto {
  final String kind;
  final String summary;
  final PlatformInt64 wallMs;

  const ActivityEntryDto({
    required this.kind,
    required this.summary,
    required this.wallMs,
  });

  @override
  int get hashCode => kind.hashCode ^ summary.hashCode ^ wallMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivityEntryDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          summary == other.summary &&
          wallMs == other.wallMs;
}

/// A device authorized for the local identity (#16).
class DeviceViewDto {
  /// The device public key, hex-encoded.
  final String device;
  final BigInt site;
  final bool revoked;
  final bool thisDevice;

  const DeviceViewDto({
    required this.device,
    required this.site,
    required this.revoked,
    required this.thisDevice,
  });

  @override
  int get hashCode =>
      device.hashCode ^ site.hashCode ^ revoked.hashCode ^ thisDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceViewDto &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          site == other.site &&
          revoked == other.revoked &&
          thisDevice == other.thisDevice;
}

/// Input for adding or editing an expense.
class ExpenseInput {
  /// `None` for a non-group (friend-to-friend) expense (#31). Ignored on edit.
  final String? groupId;
  final String description;
  final List<Payer> paidBy;
  final PlatformInt64 totalCents;
  final SplitPlanDto split;
  final String category;
  final String? notes;
  final PlatformInt64 dateMs;

  /// Create as a private draft (ignored when editing). See #15.
  final bool draft;

  /// Set when entered in a non-base currency; `total_cents`/`paid_by`/`split`
  /// must already be the converted base-currency amounts (#3).
  final OriginalAmountDto? original;

  const ExpenseInput({
    this.groupId,
    required this.description,
    required this.paidBy,
    required this.totalCents,
    required this.split,
    required this.category,
    this.notes,
    required this.dateMs,
    required this.draft,
    this.original,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      description.hashCode ^
      paidBy.hashCode ^
      totalCents.hashCode ^
      split.hashCode ^
      category.hashCode ^
      notes.hashCode ^
      dateMs.hashCode ^
      draft.hashCode ^
      original.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpenseInput &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          description == other.description &&
          paidBy == other.paidBy &&
          totalCents == other.totalCents &&
          split == other.split &&
          category == other.category &&
          notes == other.notes &&
          dateMs == other.dateMs &&
          draft == other.draft &&
          original == other.original;
}

class ExpenseViewDto {
  final String id;

  /// `None` for a non-group (friend-to-friend) expense (#31).
  final String? groupId;
  final String? groupName;
  final String description;
  final PlatformInt64 totalCents;

  /// Currency of `total_cents`/`paid_by`/`splits` (#3).
  final String currency;
  final String category;
  final PlatformInt64 dateMs;
  final String? notes;
  final PlatformInt64 myNetCents;
  final bool locked;

  /// `false` while the expense is a draft (not counted in balances). See #15.
  final bool published;

  /// Present when entered in a different currency (#3).
  final OriginalAmountDto? original;
  final List<MemberAmountDto> paidBy;
  final List<MemberAmountDto> splits;

  const ExpenseViewDto({
    required this.id,
    this.groupId,
    this.groupName,
    required this.description,
    required this.totalCents,
    required this.currency,
    required this.category,
    required this.dateMs,
    this.notes,
    required this.myNetCents,
    required this.locked,
    required this.published,
    this.original,
    required this.paidBy,
    required this.splits,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      groupId.hashCode ^
      groupName.hashCode ^
      description.hashCode ^
      totalCents.hashCode ^
      currency.hashCode ^
      category.hashCode ^
      dateMs.hashCode ^
      notes.hashCode ^
      myNetCents.hashCode ^
      locked.hashCode ^
      published.hashCode ^
      original.hashCode ^
      paidBy.hashCode ^
      splits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpenseViewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          groupId == other.groupId &&
          groupName == other.groupName &&
          description == other.description &&
          totalCents == other.totalCents &&
          currency == other.currency &&
          category == other.category &&
          dateMs == other.dateMs &&
          notes == other.notes &&
          myNetCents == other.myNetCents &&
          locked == other.locked &&
          published == other.published &&
          original == other.original &&
          paidBy == other.paidBy &&
          splits == other.splits;
}

/// A friend with the running balance to the current user (positive = owes you).
class FriendBalanceDto {
  final String userId;
  final String name;
  final PlatformInt64 netCents;

  const FriendBalanceDto({
    required this.userId,
    required this.name,
    required this.netCents,
  });

  @override
  int get hashCode => userId.hashCode ^ name.hashCode ^ netCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendBalanceDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          netCents == other.netCents;
}

class FriendDetailDto {
  final String userId;
  final String name;
  final PlatformInt64 netCents;
  final List<ExpenseViewDto> shared;

  const FriendDetailDto({
    required this.userId,
    required this.name,
    required this.netCents,
    required this.shared,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ name.hashCode ^ netCents.hashCode ^ shared.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendDetailDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          netCents == other.netCents &&
          shared == other.shared;
}

class GroupDetailDto {
  final String id;
  final String name;
  final String currency;
  final List<MemberBalanceDto> members;
  final List<ExpenseViewDto> expenses;
  final List<SettlementViewDto> settlements;
  final List<TransferDto> settleUp;

  const GroupDetailDto({
    required this.id,
    required this.name,
    required this.currency,
    required this.members,
    required this.expenses,
    required this.settlements,
    required this.settleUp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      currency.hashCode ^
      members.hashCode ^
      expenses.hashCode ^
      settlements.hashCode ^
      settleUp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDetailDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          currency == other.currency &&
          members == other.members &&
          expenses == other.expenses &&
          settlements == other.settlements &&
          settleUp == other.settleUp;
}

class GroupSummaryDto {
  final String id;
  final String name;
  final String currency;
  final int memberCount;
  final PlatformInt64 myNetCents;

  const GroupSummaryDto({
    required this.id,
    required this.name,
    required this.currency,
    required this.memberCount,
    required this.myNetCents,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      currency.hashCode ^
      memberCount.hashCode ^
      myNetCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          currency == other.currency &&
          memberCount == other.memberCount &&
          myNetCents == other.myNetCents;
}

/// A decoded invite for preview before accepting (#7).
class InviteDto {
  /// The inviter's identity as a user id (`id:<hex>`), ready to pass to
  /// `add_friend`; the embedded hex is the inviter's identity public key,
  /// usable as a fingerprint for the trust preview.
  final String inviter;

  /// `"friend"` or `"group:<id>"`.
  final String context;
  final BigInt expiryMs;

  /// Signature valid and not expired.
  final bool valid;

  const InviteDto({
    required this.inviter,
    required this.context,
    required this.expiryMs,
    required this.valid,
  });

  @override
  int get hashCode =>
      inviter.hashCode ^ context.hashCode ^ expiryMs.hashCode ^ valid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteDto &&
          runtimeType == other.runtimeType &&
          inviter == other.inviter &&
          context == other.context &&
          expiryMs == other.expiryMs &&
          valid == other.valid;
}

/// A `(user, name, amount)` triple — one payer or one split share.
class MemberAmountDto {
  final String userId;
  final String name;
  final PlatformInt64 cents;

  const MemberAmountDto({
    required this.userId,
    required this.name,
    required this.cents,
  });

  @override
  int get hashCode => userId.hashCode ^ name.hashCode ^ cents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberAmountDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          cents == other.cents;
}

class MemberBalanceDto {
  final String userId;
  final String name;
  final PlatformInt64 netCents;

  const MemberBalanceDto({
    required this.userId,
    required this.name,
    required this.netCents,
  });

  @override
  int get hashCode => userId.hashCode ^ name.hashCode ^ netCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberBalanceDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          netCents == other.netCents;
}

/// The pre-conversion amount of a foreign-currency expense (#3). `rate_micro` is
/// the base-per-original rate scaled by 1e6 (1 EUR = 1.08 USD → 1_080_000).
class OriginalAmountDto {
  final String currency;
  final PlatformInt64 amountCents;
  final PlatformInt64 rateMicro;

  const OriginalAmountDto({
    required this.currency,
    required this.amountCents,
    required this.rateMicro,
  });

  @override
  int get hashCode =>
      currency.hashCode ^ amountCents.hashCode ^ rateMicro.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OriginalAmountDto &&
          runtimeType == other.runtimeType &&
          currency == other.currency &&
          amountCents == other.amountCents &&
          rateMicro == other.rateMicro;
}

/// A payer (or exact-amount) entry: who, and how many cents.
class Payer {
  final String userId;
  final PlatformInt64 cents;

  const Payer({required this.userId, required this.cents});

  @override
  int get hashCode => userId.hashCode ^ cents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Payer &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          cents == other.cents;
}

class SettlementViewDto {
  final String id;
  final String from;
  final String fromName;
  final String to;
  final String toName;
  final PlatformInt64 amountCents;

  const SettlementViewDto({
    required this.id,
    required this.from,
    required this.fromName,
    required this.to,
    required this.toName,
    required this.amountCents,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      from.hashCode ^
      fromName.hashCode ^
      to.hashCode ^
      toName.hashCode ^
      amountCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettlementViewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          from == other.from &&
          fromName == other.fromName &&
          to == other.to &&
          toName == other.toName &&
          amountCents == other.amountCents;
}

@freezed
sealed class SplitPlanDto with _$SplitPlanDto {
  const SplitPlanDto._();

  const factory SplitPlanDto.equal({required List<String> participants}) =
      SplitPlanDto_Equal;
  const factory SplitPlanDto.exact({required List<Payer> amounts}) =
      SplitPlanDto_Exact;
  const factory SplitPlanDto.weighted({required List<Weight> weights}) =
      SplitPlanDto_Weighted;
}

class TransferDto {
  final String from;
  final String to;
  final PlatformInt64 amountCents;

  const TransferDto({
    required this.from,
    required this.to,
    required this.amountCents,
  });

  @override
  int get hashCode => from.hashCode ^ to.hashCode ^ amountCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferDto &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          amountCents == other.amountCents;
}

/// A weight entry for proportional splits (percentages or shares).
class Weight {
  final String userId;
  final BigInt weight;

  const Weight({required this.userId, required this.weight});

  @override
  int get hashCode => userId.hashCode ^ weight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Weight &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          weight == other.weight;
}
