// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

/// Input for adding or editing an expense.
class ExpenseInput {
  final String groupId;
  final String description;
  final List<Payer> paidBy;
  final PlatformInt64 totalCents;
  final SplitPlanDto split;
  final String category;
  final String? notes;
  final PlatformInt64 dateMs;

  const ExpenseInput({
    required this.groupId,
    required this.description,
    required this.paidBy,
    required this.totalCents,
    required this.split,
    required this.category,
    this.notes,
    required this.dateMs,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      description.hashCode ^
      paidBy.hashCode ^
      totalCents.hashCode ^
      split.hashCode ^
      category.hashCode ^
      notes.hashCode ^
      dateMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpenseInput &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          description == other.description &&
          paidBy == other.paidBy &&
          totalCents == other.totalCents &&
          split == other.split &&
          category == other.category &&
          notes == other.notes &&
          dateMs == other.dateMs;
}

class ExpenseViewDto {
  final String id;
  final String description;
  final PlatformInt64 totalCents;
  final String category;
  final PlatformInt64 dateMs;
  final PlatformInt64 myNetCents;
  final bool locked;

  const ExpenseViewDto({
    required this.id,
    required this.description,
    required this.totalCents,
    required this.category,
    required this.dateMs,
    required this.myNetCents,
    required this.locked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      description.hashCode ^
      totalCents.hashCode ^
      category.hashCode ^
      dateMs.hashCode ^
      myNetCents.hashCode ^
      locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpenseViewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          description == other.description &&
          totalCents == other.totalCents &&
          category == other.category &&
          dateMs == other.dateMs &&
          myNetCents == other.myNetCents &&
          locked == other.locked;
}

class GroupDetailDto {
  final String id;
  final String name;
  final List<MemberBalanceDto> members;
  final List<ExpenseViewDto> expenses;
  final List<TransferDto> settleUp;

  const GroupDetailDto({
    required this.id,
    required this.name,
    required this.members,
    required this.expenses,
    required this.settleUp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      members.hashCode ^
      expenses.hashCode ^
      settleUp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDetailDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          members == other.members &&
          expenses == other.expenses &&
          settleUp == other.settleUp;
}

class GroupSummaryDto {
  final String id;
  final String name;
  final int memberCount;
  final PlatformInt64 myNetCents;

  const GroupSummaryDto({
    required this.id,
    required this.name,
    required this.memberCount,
    required this.myNetCents,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ memberCount.hashCode ^ myNetCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          memberCount == other.memberCount &&
          myNetCents == other.myNetCents;
}

class MemberBalanceDto {
  final String userId;
  final String name;
  final PlatformInt64 netCents;

  const MemberBalanceDto({
    required this.userId,
    required this.name,
    required this.netCents,
  });

  @override
  int get hashCode => userId.hashCode ^ name.hashCode ^ netCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberBalanceDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          netCents == other.netCents;
}

/// A payer (or exact-amount) entry: who, and how many cents.
class Payer {
  final String userId;
  final PlatformInt64 cents;

  const Payer({required this.userId, required this.cents});

  @override
  int get hashCode => userId.hashCode ^ cents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Payer &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          cents == other.cents;
}

@freezed
sealed class SplitPlanDto with _$SplitPlanDto {
  const SplitPlanDto._();

  const factory SplitPlanDto.equal({required List<String> participants}) =
      SplitPlanDto_Equal;
  const factory SplitPlanDto.exact({required List<Payer> amounts}) =
      SplitPlanDto_Exact;
  const factory SplitPlanDto.weighted({required List<Weight> weights}) =
      SplitPlanDto_Weighted;
}

class TransferDto {
  final String from;
  final String to;
  final PlatformInt64 amountCents;

  const TransferDto({
    required this.from,
    required this.to,
    required this.amountCents,
  });

  @override
  int get hashCode => from.hashCode ^ to.hashCode ^ amountCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferDto &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          amountCents == other.amountCents;
}

/// A weight entry for proportional splits (percentages or shares).
class Weight {
  final String userId;
  final BigInt weight;

  const Weight({required this.userId, required this.weight});

  @override
  int get hashCode => userId.hashCode ^ weight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Weight &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          weight == other.weight;
}
