// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

/// One entry in the activity feed. `kind` is a coarse tag for icon selection:
/// `group`, `expense`, `edit`, `delete`, `settlement`, `person`.
class ActivityEntryDto {
  final String kind;
  final String summary;
  final PlatformInt64 wallMs;

  const ActivityEntryDto({
    required this.kind,
    required this.summary,
    required this.wallMs,
  });

  @override
  int get hashCode => kind.hashCode ^ summary.hashCode ^ wallMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivityEntryDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          summary == other.summary &&
          wallMs == other.wallMs;
}

/// Input for adding or editing an expense.
class ExpenseInput {
  final String groupId;
  final String description;
  final List<Payer> paidBy;
  final PlatformInt64 totalCents;
  final SplitPlanDto split;
  final String category;
  final String? notes;
  final PlatformInt64 dateMs;

  /// Create as a private draft (ignored when editing). See #15.
  final bool draft;

  const ExpenseInput({
    required this.groupId,
    required this.description,
    required this.paidBy,
    required this.totalCents,
    required this.split,
    required this.category,
    this.notes,
    required this.dateMs,
    required this.draft,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      description.hashCode ^
      paidBy.hashCode ^
      totalCents.hashCode ^
      split.hashCode ^
      category.hashCode ^
      notes.hashCode ^
      dateMs.hashCode ^
      draft.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpenseInput &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          description == other.description &&
          paidBy == other.paidBy &&
          totalCents == other.totalCents &&
          split == other.split &&
          category == other.category &&
          notes == other.notes &&
          dateMs == other.dateMs &&
          draft == other.draft;
}

class ExpenseViewDto {
  final String id;
  final String groupId;
  final String groupName;
  final String description;
  final PlatformInt64 totalCents;
  final String category;
  final PlatformInt64 dateMs;
  final String? notes;
  final PlatformInt64 myNetCents;
  final bool locked;

  /// `false` while the expense is a draft (not counted in balances). See #15.
  final bool published;
  final List<MemberAmountDto> paidBy;
  final List<MemberAmountDto> splits;

  const ExpenseViewDto({
    required this.id,
    required this.groupId,
    required this.groupName,
    required this.description,
    required this.totalCents,
    required this.category,
    required this.dateMs,
    this.notes,
    required this.myNetCents,
    required this.locked,
    required this.published,
    required this.paidBy,
    required this.splits,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      groupId.hashCode ^
      groupName.hashCode ^
      description.hashCode ^
      totalCents.hashCode ^
      category.hashCode ^
      dateMs.hashCode ^
      notes.hashCode ^
      myNetCents.hashCode ^
      locked.hashCode ^
      published.hashCode ^
      paidBy.hashCode ^
      splits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpenseViewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          groupId == other.groupId &&
          groupName == other.groupName &&
          description == other.description &&
          totalCents == other.totalCents &&
          category == other.category &&
          dateMs == other.dateMs &&
          notes == other.notes &&
          myNetCents == other.myNetCents &&
          locked == other.locked &&
          published == other.published &&
          paidBy == other.paidBy &&
          splits == other.splits;
}

/// A friend with the running balance to the current user (positive = owes you).
class FriendBalanceDto {
  final String userId;
  final String name;
  final PlatformInt64 netCents;

  const FriendBalanceDto({
    required this.userId,
    required this.name,
    required this.netCents,
  });

  @override
  int get hashCode => userId.hashCode ^ name.hashCode ^ netCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendBalanceDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          netCents == other.netCents;
}

class FriendDetailDto {
  final String userId;
  final String name;
  final PlatformInt64 netCents;
  final List<ExpenseViewDto> shared;

  const FriendDetailDto({
    required this.userId,
    required this.name,
    required this.netCents,
    required this.shared,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ name.hashCode ^ netCents.hashCode ^ shared.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendDetailDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          netCents == other.netCents &&
          shared == other.shared;
}

class GroupDetailDto {
  final String id;
  final String name;
  final List<MemberBalanceDto> members;
  final List<ExpenseViewDto> expenses;
  final List<SettlementViewDto> settlements;
  final List<TransferDto> settleUp;

  const GroupDetailDto({
    required this.id,
    required this.name,
    required this.members,
    required this.expenses,
    required this.settlements,
    required this.settleUp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      members.hashCode ^
      expenses.hashCode ^
      settlements.hashCode ^
      settleUp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDetailDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          members == other.members &&
          expenses == other.expenses &&
          settlements == other.settlements &&
          settleUp == other.settleUp;
}

class GroupSummaryDto {
  final String id;
  final String name;
  final int memberCount;
  final PlatformInt64 myNetCents;

  const GroupSummaryDto({
    required this.id,
    required this.name,
    required this.memberCount,
    required this.myNetCents,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ memberCount.hashCode ^ myNetCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          memberCount == other.memberCount &&
          myNetCents == other.myNetCents;
}

/// A `(user, name, amount)` triple — one payer or one split share.
class MemberAmountDto {
  final String userId;
  final String name;
  final PlatformInt64 cents;

  const MemberAmountDto({
    required this.userId,
    required this.name,
    required this.cents,
  });

  @override
  int get hashCode => userId.hashCode ^ name.hashCode ^ cents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberAmountDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          cents == other.cents;
}

class MemberBalanceDto {
  final String userId;
  final String name;
  final PlatformInt64 netCents;

  const MemberBalanceDto({
    required this.userId,
    required this.name,
    required this.netCents,
  });

  @override
  int get hashCode => userId.hashCode ^ name.hashCode ^ netCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberBalanceDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          netCents == other.netCents;
}

/// A payer (or exact-amount) entry: who, and how many cents.
class Payer {
  final String userId;
  final PlatformInt64 cents;

  const Payer({required this.userId, required this.cents});

  @override
  int get hashCode => userId.hashCode ^ cents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Payer &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          cents == other.cents;
}

class SettlementViewDto {
  final String id;
  final String from;
  final String fromName;
  final String to;
  final String toName;
  final PlatformInt64 amountCents;

  const SettlementViewDto({
    required this.id,
    required this.from,
    required this.fromName,
    required this.to,
    required this.toName,
    required this.amountCents,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      from.hashCode ^
      fromName.hashCode ^
      to.hashCode ^
      toName.hashCode ^
      amountCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettlementViewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          from == other.from &&
          fromName == other.fromName &&
          to == other.to &&
          toName == other.toName &&
          amountCents == other.amountCents;
}

@freezed
sealed class SplitPlanDto with _$SplitPlanDto {
  const SplitPlanDto._();

  const factory SplitPlanDto.equal({required List<String> participants}) =
      SplitPlanDto_Equal;
  const factory SplitPlanDto.exact({required List<Payer> amounts}) =
      SplitPlanDto_Exact;
  const factory SplitPlanDto.weighted({required List<Weight> weights}) =
      SplitPlanDto_Weighted;
}

class TransferDto {
  final String from;
  final String to;
  final PlatformInt64 amountCents;

  const TransferDto({
    required this.from,
    required this.to,
    required this.amountCents,
  });

  @override
  int get hashCode => from.hashCode ^ to.hashCode ^ amountCents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferDto &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          amountCents == other.amountCents;
}

/// A weight entry for proportional splits (percentages or shares).
class Weight {
  final String userId;
  final BigInt weight;

  const Weight({required this.userId, required this.weight});

  @override
  int get hashCode => userId.hashCode ^ weight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Weight &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          weight == other.weight;
}
