// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dto.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EnginePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Engine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  );

  @protected
  Engine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  );

  @protected
  Engine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ExpenseInput dco_decode_box_autoadd_expense_input(dynamic raw);

  @protected
  GroupDetailDto dco_decode_box_autoadd_group_detail_dto(dynamic raw);

  @protected
  ExpenseInput dco_decode_expense_input(dynamic raw);

  @protected
  ExpenseViewDto dco_decode_expense_view_dto(dynamic raw);

  @protected
  GroupDetailDto dco_decode_group_detail_dto(dynamic raw);

  @protected
  GroupSummaryDto dco_decode_group_summary_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ExpenseViewDto> dco_decode_list_expense_view_dto(dynamic raw);

  @protected
  List<GroupSummaryDto> dco_decode_list_group_summary_dto(dynamic raw);

  @protected
  List<MemberBalanceDto> dco_decode_list_member_balance_dto(dynamic raw);

  @protected
  List<Payer> dco_decode_list_payer(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TransferDto> dco_decode_list_transfer_dto(dynamic raw);

  @protected
  List<Weight> dco_decode_list_weight(dynamic raw);

  @protected
  MemberBalanceDto dco_decode_member_balance_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  GroupDetailDto? dco_decode_opt_box_autoadd_group_detail_dto(dynamic raw);

  @protected
  Payer dco_decode_payer(dynamic raw);

  @protected
  SplitPlanDto dco_decode_split_plan_dto(dynamic raw);

  @protected
  TransferDto dco_decode_transfer_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Weight dco_decode_weight(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Engine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  );

  @protected
  Engine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  );

  @protected
  Engine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ExpenseInput sse_decode_box_autoadd_expense_input(
    SseDeserializer deserializer,
  );

  @protected
  GroupDetailDto sse_decode_box_autoadd_group_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExpenseInput sse_decode_expense_input(SseDeserializer deserializer);

  @protected
  ExpenseViewDto sse_decode_expense_view_dto(SseDeserializer deserializer);

  @protected
  GroupDetailDto sse_decode_group_detail_dto(SseDeserializer deserializer);

  @protected
  GroupSummaryDto sse_decode_group_summary_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ExpenseViewDto> sse_decode_list_expense_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupSummaryDto> sse_decode_list_group_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MemberBalanceDto> sse_decode_list_member_balance_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<Payer> sse_decode_list_payer(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TransferDto> sse_decode_list_transfer_dto(SseDeserializer deserializer);

  @protected
  List<Weight> sse_decode_list_weight(SseDeserializer deserializer);

  @protected
  MemberBalanceDto sse_decode_member_balance_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  GroupDetailDto? sse_decode_opt_box_autoadd_group_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  Payer sse_decode_payer(SseDeserializer deserializer);

  @protected
  SplitPlanDto sse_decode_split_plan_dto(SseDeserializer deserializer);

  @protected
  TransferDto sse_decode_transfer_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Weight sse_decode_weight(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_expense_input(
    ExpenseInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_detail_dto(
    GroupDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_expense_input(ExpenseInput self, SseSerializer serializer);

  @protected
  void sse_encode_expense_view_dto(
    ExpenseViewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_detail_dto(
    GroupDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_summary_dto(
    GroupSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_expense_view_dto(
    List<ExpenseViewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_summary_dto(
    List<GroupSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_member_balance_dto(
    List<MemberBalanceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_payer(List<Payer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_dto(
    List<TransferDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_weight(List<Weight> self, SseSerializer serializer);

  @protected
  void sse_encode_member_balance_dto(
    MemberBalanceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_group_detail_dto(
    GroupDetailDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_payer(Payer self, SseSerializer serializer);

  @protected
  void sse_encode_split_plan_dto(SplitPlanDto self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_dto(TransferDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_weight(Weight self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_splittr_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_splittr_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
