// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dto.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -772973136;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'splittr_ffi',
        ioDirectory: 'splittr-core/crates/splittr-ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<ActivityEntryDto>> crateApiEngineActivity({required Engine that});

  Future<String> crateApiEngineAddExpense({
    required Engine that,
    required ExpenseInput input,
  });

  Future<void> crateApiEngineAddMember({
    required Engine that,
    required String groupId,
    required String userId,
  });

  Future<String> crateApiEngineAddPerson({
    required Engine that,
    required String name,
  });

  Future<String> crateApiEngineCreateGroup({
    required Engine that,
    required String name,
    required List<String> memberIds,
    required String currency,
  });

  Future<void> crateApiEngineDeleteExpense({
    required Engine that,
    required String expenseId,
  });

  Future<void> crateApiEngineDeleteSettlement({
    required Engine that,
    required String settlementId,
  });

  Future<void> crateApiEngineEditExpense({
    required Engine that,
    required String expenseId,
    required ExpenseInput input,
  });

  Future<FriendDetailDto?> crateApiEngineFriendDetail({
    required Engine that,
    required String userId,
  });

  Future<List<FriendBalanceDto>> crateApiEngineFriends({required Engine that});

  Future<GroupDetailDto?> crateApiEngineGroupDetail({
    required Engine that,
    required String groupId,
  });

  Future<List<GroupSummaryDto>> crateApiEngineGroups({required Engine that});

  Future<void> crateApiEngineLockExpense({
    required Engine that,
    required String expenseId,
  });

  Future<String?> crateApiEngineMyName({required Engine that});

  Future<String> crateApiEngineMyUserId({required Engine that});

  Future<Engine> crateApiEngineOpen({
    required String dbPath,
    required List<int> identitySeed,
    required List<int> dbKey,
    required BigInt site,
  });

  Future<PlatformInt64> crateApiEngineOverallNetCents({required Engine that});

  Future<void> crateApiEnginePublishExpense({
    required Engine that,
    required String expenseId,
  });

  Future<String> crateApiEngineRecordNonGroupSettlement({
    required Engine that,
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  });

  Future<String> crateApiEngineRecordSettlement({
    required Engine that,
    required String groupId,
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  });

  Future<void> crateApiEngineRemoveMember({
    required Engine that,
    required String groupId,
    required String userId,
  });

  Future<void> crateApiEngineRenameGroup({
    required Engine that,
    required String groupId,
    required String name,
  });

  Future<void> crateApiEngineSetClosedPeriod({
    required Engine that,
    required String groupId,
    required PlatformInt64 untilMs,
  });

  Future<void> crateApiEngineSetGroupCurrency({
    required Engine that,
    required String groupId,
    required String currency,
  });

  Future<void> crateApiEngineSetMyName({
    required Engine that,
    required String name,
  });

  Future<void> crateApiEngineUnlockExpense({
    required Engine that,
    required String expenseId,
  });

  Future<PlatformInt64> crateApiConvertCurrency({
    required PlatformInt64 amountCents,
    required PlatformInt64 rateMicro,
    required String fromCurrency,
    required String toCurrency,
  });

  Future<int> crateApiCurrencyMinorUnits({required String code});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Engine;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Engine;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_EnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<ActivityEntryDto>> crateApiEngineActivity({
    required Engine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_activity_entry_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineActivityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineActivityConstMeta =>
      const TaskConstMeta(debugName: "Engine_activity", argNames: ["that"]);

  @override
  Future<String> crateApiEngineAddExpense({
    required Engine that,
    required ExpenseInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_box_autoadd_expense_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineAddExpenseConstMeta,
        argValues: [that, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineAddExpenseConstMeta => const TaskConstMeta(
    debugName: "Engine_add_expense",
    argNames: ["that", "input"],
  );

  @override
  Future<void> crateApiEngineAddMember({
    required Engine that,
    required String groupId,
    required String userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineAddMemberConstMeta,
        argValues: [that, groupId, userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineAddMemberConstMeta => const TaskConstMeta(
    debugName: "Engine_add_member",
    argNames: ["that", "groupId", "userId"],
  );

  @override
  Future<String> crateApiEngineAddPerson({
    required Engine that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineAddPersonConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineAddPersonConstMeta => const TaskConstMeta(
    debugName: "Engine_add_person",
    argNames: ["that", "name"],
  );

  @override
  Future<String> crateApiEngineCreateGroup({
    required Engine that,
    required String name,
    required List<String> memberIds,
    required String currency,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_list_String(memberIds, serializer);
          sse_encode_String(currency, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineCreateGroupConstMeta,
        argValues: [that, name, memberIds, currency],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCreateGroupConstMeta => const TaskConstMeta(
    debugName: "Engine_create_group",
    argNames: ["that", "name", "memberIds", "currency"],
  );

  @override
  Future<void> crateApiEngineDeleteExpense({
    required Engine that,
    required String expenseId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(expenseId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineDeleteExpenseConstMeta,
        argValues: [that, expenseId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineDeleteExpenseConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_delete_expense",
        argNames: ["that", "expenseId"],
      );

  @override
  Future<void> crateApiEngineDeleteSettlement({
    required Engine that,
    required String settlementId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(settlementId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineDeleteSettlementConstMeta,
        argValues: [that, settlementId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineDeleteSettlementConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_delete_settlement",
        argNames: ["that", "settlementId"],
      );

  @override
  Future<void> crateApiEngineEditExpense({
    required Engine that,
    required String expenseId,
    required ExpenseInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(expenseId, serializer);
          sse_encode_box_autoadd_expense_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineEditExpenseConstMeta,
        argValues: [that, expenseId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEditExpenseConstMeta => const TaskConstMeta(
    debugName: "Engine_edit_expense",
    argNames: ["that", "expenseId", "input"],
  );

  @override
  Future<FriendDetailDto?> crateApiEngineFriendDetail({
    required Engine that,
    required String userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_friend_detail_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineFriendDetailConstMeta,
        argValues: [that, userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineFriendDetailConstMeta => const TaskConstMeta(
    debugName: "Engine_friend_detail",
    argNames: ["that", "userId"],
  );

  @override
  Future<List<FriendBalanceDto>> crateApiEngineFriends({required Engine that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_friend_balance_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineFriendsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineFriendsConstMeta =>
      const TaskConstMeta(debugName: "Engine_friends", argNames: ["that"]);

  @override
  Future<GroupDetailDto?> crateApiEngineGroupDetail({
    required Engine that,
    required String groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_group_detail_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineGroupDetailConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGroupDetailConstMeta => const TaskConstMeta(
    debugName: "Engine_group_detail",
    argNames: ["that", "groupId"],
  );

  @override
  Future<List<GroupSummaryDto>> crateApiEngineGroups({required Engine that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_group_summary_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineGroupsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGroupsConstMeta =>
      const TaskConstMeta(debugName: "Engine_groups", argNames: ["that"]);

  @override
  Future<void> crateApiEngineLockExpense({
    required Engine that,
    required String expenseId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(expenseId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineLockExpenseConstMeta,
        argValues: [that, expenseId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineLockExpenseConstMeta => const TaskConstMeta(
    debugName: "Engine_lock_expense",
    argNames: ["that", "expenseId"],
  );

  @override
  Future<String?> crateApiEngineMyName({required Engine that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineMyNameConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineMyNameConstMeta =>
      const TaskConstMeta(debugName: "Engine_my_name", argNames: ["that"]);

  @override
  Future<String> crateApiEngineMyUserId({required Engine that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineMyUserIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineMyUserIdConstMeta =>
      const TaskConstMeta(debugName: "Engine_my_user_id", argNames: ["that"]);

  @override
  Future<Engine> crateApiEngineOpen({
    required String dbPath,
    required List<int> identitySeed,
    required List<int> dbKey,
    required BigInt site,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_list_prim_u_8_loose(identitySeed, serializer);
          sse_encode_list_prim_u_8_loose(dbKey, serializer);
          sse_encode_u_64(site, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineOpenConstMeta,
        argValues: [dbPath, identitySeed, dbKey, site],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineOpenConstMeta => const TaskConstMeta(
    debugName: "Engine_open",
    argNames: ["dbPath", "identitySeed", "dbKey", "site"],
  );

  @override
  Future<PlatformInt64> crateApiEngineOverallNetCents({required Engine that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineOverallNetCentsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineOverallNetCentsConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_overall_net_cents",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiEnginePublishExpense({
    required Engine that,
    required String expenseId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(expenseId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePublishExpenseConstMeta,
        argValues: [that, expenseId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePublishExpenseConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_publish_expense",
        argNames: ["that", "expenseId"],
      );

  @override
  Future<String> crateApiEngineRecordNonGroupSettlement({
    required Engine that,
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          sse_encode_i_64(amountCents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineRecordNonGroupSettlementConstMeta,
        argValues: [that, from, to, amountCents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRecordNonGroupSettlementConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_record_non_group_settlement",
        argNames: ["that", "from", "to", "amountCents"],
      );

  @override
  Future<String> crateApiEngineRecordSettlement({
    required Engine that,
    required String groupId,
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          sse_encode_i_64(amountCents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineRecordSettlementConstMeta,
        argValues: [that, groupId, from, to, amountCents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRecordSettlementConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_record_settlement",
        argNames: ["that", "groupId", "from", "to", "amountCents"],
      );

  @override
  Future<void> crateApiEngineRemoveMember({
    required Engine that,
    required String groupId,
    required String userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineRemoveMemberConstMeta,
        argValues: [that, groupId, userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRemoveMemberConstMeta => const TaskConstMeta(
    debugName: "Engine_remove_member",
    argNames: ["that", "groupId", "userId"],
  );

  @override
  Future<void> crateApiEngineRenameGroup({
    required Engine that,
    required String groupId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineRenameGroupConstMeta,
        argValues: [that, groupId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRenameGroupConstMeta => const TaskConstMeta(
    debugName: "Engine_rename_group",
    argNames: ["that", "groupId", "name"],
  );

  @override
  Future<void> crateApiEngineSetClosedPeriod({
    required Engine that,
    required String groupId,
    required PlatformInt64 untilMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_i_64(untilMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineSetClosedPeriodConstMeta,
        argValues: [that, groupId, untilMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetClosedPeriodConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_set_closed_period",
        argNames: ["that", "groupId", "untilMs"],
      );

  @override
  Future<void> crateApiEngineSetGroupCurrency({
    required Engine that,
    required String groupId,
    required String currency,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(currency, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineSetGroupCurrencyConstMeta,
        argValues: [that, groupId, currency],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetGroupCurrencyConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_set_group_currency",
        argNames: ["that", "groupId", "currency"],
      );

  @override
  Future<void> crateApiEngineSetMyName({
    required Engine that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineSetMyNameConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetMyNameConstMeta => const TaskConstMeta(
    debugName: "Engine_set_my_name",
    argNames: ["that", "name"],
  );

  @override
  Future<void> crateApiEngineUnlockExpense({
    required Engine that,
    required String expenseId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
            that,
            serializer,
          );
          sse_encode_String(expenseId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineUnlockExpenseConstMeta,
        argValues: [that, expenseId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineUnlockExpenseConstMeta =>
      const TaskConstMeta(
        debugName: "Engine_unlock_expense",
        argNames: ["that", "expenseId"],
      );

  @override
  Future<PlatformInt64> crateApiConvertCurrency({
    required PlatformInt64 amountCents,
    required PlatformInt64 rateMicro,
    required String fromCurrency,
    required String toCurrency,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(amountCents, serializer);
          sse_encode_i_64(rateMicro, serializer);
          sse_encode_String(fromCurrency, serializer);
          sse_encode_String(toCurrency, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConvertCurrencyConstMeta,
        argValues: [amountCents, rateMicro, fromCurrency, toCurrency],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConvertCurrencyConstMeta => const TaskConstMeta(
    debugName: "convert_currency",
    argNames: ["amountCents", "rateMicro", "fromCurrency", "toCurrency"],
  );

  @override
  Future<int> crateApiCurrencyMinorUnits({required String code}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCurrencyMinorUnitsConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCurrencyMinorUnitsConstMeta => const TaskConstMeta(
    debugName: "currency_minor_units",
    argNames: ["code"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Engine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Engine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Engine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Engine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Engine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActivityEntryDto dco_decode_activity_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ActivityEntryDto(
      kind: dco_decode_String(arr[0]),
      summary: dco_decode_String(arr[1]),
      wallMs: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ExpenseInput dco_decode_box_autoadd_expense_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_expense_input(raw);
  }

  @protected
  FriendDetailDto dco_decode_box_autoadd_friend_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_friend_detail_dto(raw);
  }

  @protected
  GroupDetailDto dco_decode_box_autoadd_group_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_group_detail_dto(raw);
  }

  @protected
  OriginalAmountDto dco_decode_box_autoadd_original_amount_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_original_amount_dto(raw);
  }

  @protected
  ExpenseInput dco_decode_expense_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ExpenseInput(
      groupId: dco_decode_opt_String(arr[0]),
      description: dco_decode_String(arr[1]),
      paidBy: dco_decode_list_payer(arr[2]),
      totalCents: dco_decode_i_64(arr[3]),
      split: dco_decode_split_plan_dto(arr[4]),
      category: dco_decode_String(arr[5]),
      notes: dco_decode_opt_String(arr[6]),
      dateMs: dco_decode_i_64(arr[7]),
      draft: dco_decode_bool(arr[8]),
      original: dco_decode_opt_box_autoadd_original_amount_dto(arr[9]),
    );
  }

  @protected
  ExpenseViewDto dco_decode_expense_view_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return ExpenseViewDto(
      id: dco_decode_String(arr[0]),
      groupId: dco_decode_opt_String(arr[1]),
      groupName: dco_decode_opt_String(arr[2]),
      description: dco_decode_String(arr[3]),
      totalCents: dco_decode_i_64(arr[4]),
      currency: dco_decode_String(arr[5]),
      category: dco_decode_String(arr[6]),
      dateMs: dco_decode_i_64(arr[7]),
      notes: dco_decode_opt_String(arr[8]),
      myNetCents: dco_decode_i_64(arr[9]),
      locked: dco_decode_bool(arr[10]),
      published: dco_decode_bool(arr[11]),
      original: dco_decode_opt_box_autoadd_original_amount_dto(arr[12]),
      paidBy: dco_decode_list_member_amount_dto(arr[13]),
      splits: dco_decode_list_member_amount_dto(arr[14]),
    );
  }

  @protected
  FriendBalanceDto dco_decode_friend_balance_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FriendBalanceDto(
      userId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      netCents: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  FriendDetailDto dco_decode_friend_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FriendDetailDto(
      userId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      netCents: dco_decode_i_64(arr[2]),
      shared: dco_decode_list_expense_view_dto(arr[3]),
    );
  }

  @protected
  GroupDetailDto dco_decode_group_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return GroupDetailDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      currency: dco_decode_String(arr[2]),
      members: dco_decode_list_member_balance_dto(arr[3]),
      expenses: dco_decode_list_expense_view_dto(arr[4]),
      settlements: dco_decode_list_settlement_view_dto(arr[5]),
      settleUp: dco_decode_list_transfer_dto(arr[6]),
    );
  }

  @protected
  GroupSummaryDto dco_decode_group_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GroupSummaryDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      currency: dco_decode_String(arr[2]),
      memberCount: dco_decode_u_32(arr[3]),
      myNetCents: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ActivityEntryDto> dco_decode_list_activity_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_activity_entry_dto).toList();
  }

  @protected
  List<ExpenseViewDto> dco_decode_list_expense_view_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_expense_view_dto).toList();
  }

  @protected
  List<FriendBalanceDto> dco_decode_list_friend_balance_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_friend_balance_dto).toList();
  }

  @protected
  List<GroupSummaryDto> dco_decode_list_group_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_group_summary_dto).toList();
  }

  @protected
  List<MemberAmountDto> dco_decode_list_member_amount_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_amount_dto).toList();
  }

  @protected
  List<MemberBalanceDto> dco_decode_list_member_balance_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_balance_dto).toList();
  }

  @protected
  List<Payer> dco_decode_list_payer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_payer).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SettlementViewDto> dco_decode_list_settlement_view_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_settlement_view_dto).toList();
  }

  @protected
  List<TransferDto> dco_decode_list_transfer_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_transfer_dto).toList();
  }

  @protected
  List<Weight> dco_decode_list_weight(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_weight).toList();
  }

  @protected
  MemberAmountDto dco_decode_member_amount_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MemberAmountDto(
      userId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      cents: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  MemberBalanceDto dco_decode_member_balance_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MemberBalanceDto(
      userId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      netCents: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FriendDetailDto? dco_decode_opt_box_autoadd_friend_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_friend_detail_dto(raw);
  }

  @protected
  GroupDetailDto? dco_decode_opt_box_autoadd_group_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_group_detail_dto(raw);
  }

  @protected
  OriginalAmountDto? dco_decode_opt_box_autoadd_original_amount_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_original_amount_dto(raw);
  }

  @protected
  OriginalAmountDto dco_decode_original_amount_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OriginalAmountDto(
      currency: dco_decode_String(arr[0]),
      amountCents: dco_decode_i_64(arr[1]),
      rateMicro: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  Payer dco_decode_payer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Payer(
      userId: dco_decode_String(arr[0]),
      cents: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  SettlementViewDto dco_decode_settlement_view_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SettlementViewDto(
      id: dco_decode_String(arr[0]),
      from: dco_decode_String(arr[1]),
      fromName: dco_decode_String(arr[2]),
      to: dco_decode_String(arr[3]),
      toName: dco_decode_String(arr[4]),
      amountCents: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  SplitPlanDto dco_decode_split_plan_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SplitPlanDto_Equal(participants: dco_decode_list_String(raw[1]));
      case 1:
        return SplitPlanDto_Exact(amounts: dco_decode_list_payer(raw[1]));
      case 2:
        return SplitPlanDto_Weighted(weights: dco_decode_list_weight(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TransferDto dco_decode_transfer_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TransferDto(
      from: dco_decode_String(arr[0]),
      to: dco_decode_String(arr[1]),
      amountCents: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Weight dco_decode_weight(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Weight(
      userId: dco_decode_String(arr[0]),
      weight: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Engine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Engine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Engine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActivityEntryDto sse_decode_activity_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_wallMs = sse_decode_i_64(deserializer);
    return ActivityEntryDto(
      kind: var_kind,
      summary: var_summary,
      wallMs: var_wallMs,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ExpenseInput sse_decode_box_autoadd_expense_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_expense_input(deserializer));
  }

  @protected
  FriendDetailDto sse_decode_box_autoadd_friend_detail_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_friend_detail_dto(deserializer));
  }

  @protected
  GroupDetailDto sse_decode_box_autoadd_group_detail_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_group_detail_dto(deserializer));
  }

  @protected
  OriginalAmountDto sse_decode_box_autoadd_original_amount_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_original_amount_dto(deserializer));
  }

  @protected
  ExpenseInput sse_decode_expense_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupId = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_paidBy = sse_decode_list_payer(deserializer);
    var var_totalCents = sse_decode_i_64(deserializer);
    var var_split = sse_decode_split_plan_dto(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_dateMs = sse_decode_i_64(deserializer);
    var var_draft = sse_decode_bool(deserializer);
    var var_original = sse_decode_opt_box_autoadd_original_amount_dto(
      deserializer,
    );
    return ExpenseInput(
      groupId: var_groupId,
      description: var_description,
      paidBy: var_paidBy,
      totalCents: var_totalCents,
      split: var_split,
      category: var_category,
      notes: var_notes,
      dateMs: var_dateMs,
      draft: var_draft,
      original: var_original,
    );
  }

  @protected
  ExpenseViewDto sse_decode_expense_view_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_groupId = sse_decode_opt_String(deserializer);
    var var_groupName = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_totalCents = sse_decode_i_64(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_dateMs = sse_decode_i_64(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_myNetCents = sse_decode_i_64(deserializer);
    var var_locked = sse_decode_bool(deserializer);
    var var_published = sse_decode_bool(deserializer);
    var var_original = sse_decode_opt_box_autoadd_original_amount_dto(
      deserializer,
    );
    var var_paidBy = sse_decode_list_member_amount_dto(deserializer);
    var var_splits = sse_decode_list_member_amount_dto(deserializer);
    return ExpenseViewDto(
      id: var_id,
      groupId: var_groupId,
      groupName: var_groupName,
      description: var_description,
      totalCents: var_totalCents,
      currency: var_currency,
      category: var_category,
      dateMs: var_dateMs,
      notes: var_notes,
      myNetCents: var_myNetCents,
      locked: var_locked,
      published: var_published,
      original: var_original,
      paidBy: var_paidBy,
      splits: var_splits,
    );
  }

  @protected
  FriendBalanceDto sse_decode_friend_balance_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_netCents = sse_decode_i_64(deserializer);
    return FriendBalanceDto(
      userId: var_userId,
      name: var_name,
      netCents: var_netCents,
    );
  }

  @protected
  FriendDetailDto sse_decode_friend_detail_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_netCents = sse_decode_i_64(deserializer);
    var var_shared = sse_decode_list_expense_view_dto(deserializer);
    return FriendDetailDto(
      userId: var_userId,
      name: var_name,
      netCents: var_netCents,
      shared: var_shared,
    );
  }

  @protected
  GroupDetailDto sse_decode_group_detail_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_members = sse_decode_list_member_balance_dto(deserializer);
    var var_expenses = sse_decode_list_expense_view_dto(deserializer);
    var var_settlements = sse_decode_list_settlement_view_dto(deserializer);
    var var_settleUp = sse_decode_list_transfer_dto(deserializer);
    return GroupDetailDto(
      id: var_id,
      name: var_name,
      currency: var_currency,
      members: var_members,
      expenses: var_expenses,
      settlements: var_settlements,
      settleUp: var_settleUp,
    );
  }

  @protected
  GroupSummaryDto sse_decode_group_summary_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_memberCount = sse_decode_u_32(deserializer);
    var var_myNetCents = sse_decode_i_64(deserializer);
    return GroupSummaryDto(
      id: var_id,
      name: var_name,
      currency: var_currency,
      memberCount: var_memberCount,
      myNetCents: var_myNetCents,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ActivityEntryDto> sse_decode_list_activity_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ActivityEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_activity_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExpenseViewDto> sse_decode_list_expense_view_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExpenseViewDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_expense_view_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<FriendBalanceDto> sse_decode_list_friend_balance_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FriendBalanceDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_friend_balance_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<GroupSummaryDto> sse_decode_list_group_summary_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GroupSummaryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_group_summary_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberAmountDto> sse_decode_list_member_amount_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberAmountDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_amount_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberBalanceDto> sse_decode_list_member_balance_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberBalanceDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_balance_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<Payer> sse_decode_list_payer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Payer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_payer(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SettlementViewDto> sse_decode_list_settlement_view_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SettlementViewDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_settlement_view_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<TransferDto> sse_decode_list_transfer_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TransferDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transfer_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<Weight> sse_decode_list_weight(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Weight>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_weight(deserializer));
    }
    return ans_;
  }

  @protected
  MemberAmountDto sse_decode_member_amount_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_cents = sse_decode_i_64(deserializer);
    return MemberAmountDto(
      userId: var_userId,
      name: var_name,
      cents: var_cents,
    );
  }

  @protected
  MemberBalanceDto sse_decode_member_balance_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_netCents = sse_decode_i_64(deserializer);
    return MemberBalanceDto(
      userId: var_userId,
      name: var_name,
      netCents: var_netCents,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FriendDetailDto? sse_decode_opt_box_autoadd_friend_detail_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_friend_detail_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GroupDetailDto? sse_decode_opt_box_autoadd_group_detail_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_group_detail_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OriginalAmountDto? sse_decode_opt_box_autoadd_original_amount_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_original_amount_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OriginalAmountDto sse_decode_original_amount_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currency = sse_decode_String(deserializer);
    var var_amountCents = sse_decode_i_64(deserializer);
    var var_rateMicro = sse_decode_i_64(deserializer);
    return OriginalAmountDto(
      currency: var_currency,
      amountCents: var_amountCents,
      rateMicro: var_rateMicro,
    );
  }

  @protected
  Payer sse_decode_payer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_cents = sse_decode_i_64(deserializer);
    return Payer(userId: var_userId, cents: var_cents);
  }

  @protected
  SettlementViewDto sse_decode_settlement_view_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_from = sse_decode_String(deserializer);
    var var_fromName = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_toName = sse_decode_String(deserializer);
    var var_amountCents = sse_decode_i_64(deserializer);
    return SettlementViewDto(
      id: var_id,
      from: var_from,
      fromName: var_fromName,
      to: var_to,
      toName: var_toName,
      amountCents: var_amountCents,
    );
  }

  @protected
  SplitPlanDto sse_decode_split_plan_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_participants = sse_decode_list_String(deserializer);
        return SplitPlanDto_Equal(participants: var_participants);
      case 1:
        var var_amounts = sse_decode_list_payer(deserializer);
        return SplitPlanDto_Exact(amounts: var_amounts);
      case 2:
        var var_weights = sse_decode_list_weight(deserializer);
        return SplitPlanDto_Weighted(weights: var_weights);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TransferDto sse_decode_transfer_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_from = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_amountCents = sse_decode_i_64(deserializer);
    return TransferDto(
      from: var_from,
      to: var_to,
      amountCents: var_amountCents,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  Weight sse_decode_weight(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_weight = sse_decode_u_64(deserializer);
    return Weight(userId: var_userId, weight: var_weight);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_activity_entry_dto(
    ActivityEntryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_i_64(self.wallMs, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_expense_input(
    ExpenseInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_expense_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_friend_detail_dto(
    FriendDetailDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_friend_detail_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_group_detail_dto(
    GroupDetailDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_group_detail_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_original_amount_dto(
    OriginalAmountDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_original_amount_dto(self, serializer);
  }

  @protected
  void sse_encode_expense_input(ExpenseInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.groupId, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_list_payer(self.paidBy, serializer);
    sse_encode_i_64(self.totalCents, serializer);
    sse_encode_split_plan_dto(self.split, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_i_64(self.dateMs, serializer);
    sse_encode_bool(self.draft, serializer);
    sse_encode_opt_box_autoadd_original_amount_dto(self.original, serializer);
  }

  @protected
  void sse_encode_expense_view_dto(
    ExpenseViewDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.groupId, serializer);
    sse_encode_opt_String(self.groupName, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_i_64(self.totalCents, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_i_64(self.dateMs, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_i_64(self.myNetCents, serializer);
    sse_encode_bool(self.locked, serializer);
    sse_encode_bool(self.published, serializer);
    sse_encode_opt_box_autoadd_original_amount_dto(self.original, serializer);
    sse_encode_list_member_amount_dto(self.paidBy, serializer);
    sse_encode_list_member_amount_dto(self.splits, serializer);
  }

  @protected
  void sse_encode_friend_balance_dto(
    FriendBalanceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_64(self.netCents, serializer);
  }

  @protected
  void sse_encode_friend_detail_dto(
    FriendDetailDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_64(self.netCents, serializer);
    sse_encode_list_expense_view_dto(self.shared, serializer);
  }

  @protected
  void sse_encode_group_detail_dto(
    GroupDetailDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_list_member_balance_dto(self.members, serializer);
    sse_encode_list_expense_view_dto(self.expenses, serializer);
    sse_encode_list_settlement_view_dto(self.settlements, serializer);
    sse_encode_list_transfer_dto(self.settleUp, serializer);
  }

  @protected
  void sse_encode_group_summary_dto(
    GroupSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_u_32(self.memberCount, serializer);
    sse_encode_i_64(self.myNetCents, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_activity_entry_dto(
    List<ActivityEntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_activity_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_expense_view_dto(
    List<ExpenseViewDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_expense_view_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_friend_balance_dto(
    List<FriendBalanceDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_friend_balance_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_group_summary_dto(
    List<GroupSummaryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_group_summary_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_amount_dto(
    List<MemberAmountDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_amount_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_balance_dto(
    List<MemberBalanceDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_balance_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_payer(List<Payer> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_payer(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_settlement_view_dto(
    List<SettlementViewDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_settlement_view_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_transfer_dto(
    List<TransferDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transfer_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_weight(List<Weight> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_weight(item, serializer);
    }
  }

  @protected
  void sse_encode_member_amount_dto(
    MemberAmountDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_64(self.cents, serializer);
  }

  @protected
  void sse_encode_member_balance_dto(
    MemberBalanceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_64(self.netCents, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_friend_detail_dto(
    FriendDetailDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_friend_detail_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_group_detail_dto(
    GroupDetailDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_group_detail_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_original_amount_dto(
    OriginalAmountDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_original_amount_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_original_amount_dto(
    OriginalAmountDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.currency, serializer);
    sse_encode_i_64(self.amountCents, serializer);
    sse_encode_i_64(self.rateMicro, serializer);
  }

  @protected
  void sse_encode_payer(Payer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_i_64(self.cents, serializer);
  }

  @protected
  void sse_encode_settlement_view_dto(
    SettlementViewDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.from, serializer);
    sse_encode_String(self.fromName, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_String(self.toName, serializer);
    sse_encode_i_64(self.amountCents, serializer);
  }

  @protected
  void sse_encode_split_plan_dto(SplitPlanDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SplitPlanDto_Equal(participants: final participants):
        sse_encode_i_32(0, serializer);
        sse_encode_list_String(participants, serializer);
      case SplitPlanDto_Exact(amounts: final amounts):
        sse_encode_i_32(1, serializer);
        sse_encode_list_payer(amounts, serializer);
      case SplitPlanDto_Weighted(weights: final weights):
        sse_encode_i_32(2, serializer);
        sse_encode_list_weight(weights, serializer);
    }
  }

  @protected
  void sse_encode_transfer_dto(TransferDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.from, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_i_64(self.amountCents, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_weight(Weight self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_u_64(self.weight, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class EngineImpl extends RustOpaque implements Engine {
  // Not to be used by end users
  EngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  EngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Engine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Engine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_EnginePtr,
  );

  Future<List<ActivityEntryDto>> activity() =>
      RustLib.instance.api.crateApiEngineActivity(that: this);

  Future<String> addExpense({required ExpenseInput input}) =>
      RustLib.instance.api.crateApiEngineAddExpense(that: this, input: input);

  Future<void> addMember({required String groupId, required String userId}) =>
      RustLib.instance.api.crateApiEngineAddMember(
        that: this,
        groupId: groupId,
        userId: userId,
      );

  Future<String> addPerson({required String name}) =>
      RustLib.instance.api.crateApiEngineAddPerson(that: this, name: name);

  Future<String> createGroup({
    required String name,
    required List<String> memberIds,
    required String currency,
  }) => RustLib.instance.api.crateApiEngineCreateGroup(
    that: this,
    name: name,
    memberIds: memberIds,
    currency: currency,
  );

  Future<void> deleteExpense({required String expenseId}) => RustLib
      .instance
      .api
      .crateApiEngineDeleteExpense(that: this, expenseId: expenseId);

  Future<void> deleteSettlement({required String settlementId}) => RustLib
      .instance
      .api
      .crateApiEngineDeleteSettlement(that: this, settlementId: settlementId);

  /// Replace an expense with a new version. `input.group_id` is ignored (an
  /// expense cannot change groups).
  Future<void> editExpense({
    required String expenseId,
    required ExpenseInput input,
  }) => RustLib.instance.api.crateApiEngineEditExpense(
    that: this,
    expenseId: expenseId,
    input: input,
  );

  Future<FriendDetailDto?> friendDetail({required String userId}) => RustLib
      .instance
      .api
      .crateApiEngineFriendDetail(that: this, userId: userId);

  Future<List<FriendBalanceDto>> friends() =>
      RustLib.instance.api.crateApiEngineFriends(that: this);

  Future<GroupDetailDto?> groupDetail({required String groupId}) => RustLib
      .instance
      .api
      .crateApiEngineGroupDetail(that: this, groupId: groupId);

  Future<List<GroupSummaryDto>> groups() =>
      RustLib.instance.api.crateApiEngineGroups(that: this);

  Future<void> lockExpense({required String expenseId}) => RustLib.instance.api
      .crateApiEngineLockExpense(that: this, expenseId: expenseId);

  Future<String?> myName() =>
      RustLib.instance.api.crateApiEngineMyName(that: this);

  Future<String> myUserId() =>
      RustLib.instance.api.crateApiEngineMyUserId(that: this);

  /// The local user's overall net across all expenses/settlements, including
  /// non-group ones (#31). Positive = owed to you.
  Future<PlatformInt64> overallNetCents() =>
      RustLib.instance.api.crateApiEngineOverallNetCents(that: this);

  /// Publish a draft expense so it counts toward balances (#15).
  Future<void> publishExpense({required String expenseId}) => RustLib
      .instance
      .api
      .crateApiEnginePublishExpense(that: this, expenseId: expenseId);

  /// Record a non-group (friend-to-friend) payment (#31).
  Future<String> recordNonGroupSettlement({
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  }) => RustLib.instance.api.crateApiEngineRecordNonGroupSettlement(
    that: this,
    from: from,
    to: to,
    amountCents: amountCents,
  );

  Future<String> recordSettlement({
    required String groupId,
    required String from,
    required String to,
    required PlatformInt64 amountCents,
  }) => RustLib.instance.api.crateApiEngineRecordSettlement(
    that: this,
    groupId: groupId,
    from: from,
    to: to,
    amountCents: amountCents,
  );

  Future<void> removeMember({
    required String groupId,
    required String userId,
  }) => RustLib.instance.api.crateApiEngineRemoveMember(
    that: this,
    groupId: groupId,
    userId: userId,
  );

  Future<void> renameGroup({required String groupId, required String name}) =>
      RustLib.instance.api.crateApiEngineRenameGroup(
        that: this,
        groupId: groupId,
        name: name,
      );

  /// Close a group's accounting period (#15): expenses dated at or before
  /// `until_ms` become uneditable. Pass `0` to reopen.
  Future<void> setClosedPeriod({
    required String groupId,
    required PlatformInt64 untilMs,
  }) => RustLib.instance.api.crateApiEngineSetClosedPeriod(
    that: this,
    groupId: groupId,
    untilMs: untilMs,
  );

  Future<void> setGroupCurrency({
    required String groupId,
    required String currency,
  }) => RustLib.instance.api.crateApiEngineSetGroupCurrency(
    that: this,
    groupId: groupId,
    currency: currency,
  );

  Future<void> setMyName({required String name}) =>
      RustLib.instance.api.crateApiEngineSetMyName(that: this, name: name);

  Future<void> unlockExpense({required String expenseId}) => RustLib
      .instance
      .api
      .crateApiEngineUnlockExpense(that: this, expenseId: expenseId);
}
