// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dto.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EnginePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Engine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  );

  @protected
  Engine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  );

  @protected
  Engine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActivityEntryDto dco_decode_activity_entry_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ExpenseInput dco_decode_box_autoadd_expense_input(dynamic raw);

  @protected
  FriendDetailDto dco_decode_box_autoadd_friend_detail_dto(dynamic raw);

  @protected
  GroupDetailDto dco_decode_box_autoadd_group_detail_dto(dynamic raw);

  @protected
  OriginalAmountDto dco_decode_box_autoadd_original_amount_dto(dynamic raw);

  @protected
  DeviceViewDto dco_decode_device_view_dto(dynamic raw);

  @protected
  ExpenseInput dco_decode_expense_input(dynamic raw);

  @protected
  ExpenseViewDto dco_decode_expense_view_dto(dynamic raw);

  @protected
  FriendBalanceDto dco_decode_friend_balance_dto(dynamic raw);

  @protected
  FriendDetailDto dco_decode_friend_detail_dto(dynamic raw);

  @protected
  GroupDetailDto dco_decode_group_detail_dto(dynamic raw);

  @protected
  GroupSummaryDto dco_decode_group_summary_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActivityEntryDto> dco_decode_list_activity_entry_dto(dynamic raw);

  @protected
  List<DeviceViewDto> dco_decode_list_device_view_dto(dynamic raw);

  @protected
  List<ExpenseViewDto> dco_decode_list_expense_view_dto(dynamic raw);

  @protected
  List<FriendBalanceDto> dco_decode_list_friend_balance_dto(dynamic raw);

  @protected
  List<GroupSummaryDto> dco_decode_list_group_summary_dto(dynamic raw);

  @protected
  List<MemberAmountDto> dco_decode_list_member_amount_dto(dynamic raw);

  @protected
  List<MemberBalanceDto> dco_decode_list_member_balance_dto(dynamic raw);

  @protected
  List<Payer> dco_decode_list_payer(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SettlementViewDto> dco_decode_list_settlement_view_dto(dynamic raw);

  @protected
  List<TransferDto> dco_decode_list_transfer_dto(dynamic raw);

  @protected
  List<Weight> dco_decode_list_weight(dynamic raw);

  @protected
  MemberAmountDto dco_decode_member_amount_dto(dynamic raw);

  @protected
  MemberBalanceDto dco_decode_member_balance_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FriendDetailDto? dco_decode_opt_box_autoadd_friend_detail_dto(dynamic raw);

  @protected
  GroupDetailDto? dco_decode_opt_box_autoadd_group_detail_dto(dynamic raw);

  @protected
  OriginalAmountDto? dco_decode_opt_box_autoadd_original_amount_dto(
    dynamic raw,
  );

  @protected
  OriginalAmountDto dco_decode_original_amount_dto(dynamic raw);

  @protected
  Payer dco_decode_payer(dynamic raw);

  @protected
  SettlementViewDto dco_decode_settlement_view_dto(dynamic raw);

  @protected
  SplitPlanDto dco_decode_split_plan_dto(dynamic raw);

  @protected
  TransferDto dco_decode_transfer_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Weight dco_decode_weight(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Engine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  );

  @protected
  Engine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  );

  @protected
  Engine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActivityEntryDto sse_decode_activity_entry_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ExpenseInput sse_decode_box_autoadd_expense_input(
    SseDeserializer deserializer,
  );

  @protected
  FriendDetailDto sse_decode_box_autoadd_friend_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupDetailDto sse_decode_box_autoadd_group_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  OriginalAmountDto sse_decode_box_autoadd_original_amount_dto(
    SseDeserializer deserializer,
  );

  @protected
  DeviceViewDto sse_decode_device_view_dto(SseDeserializer deserializer);

  @protected
  ExpenseInput sse_decode_expense_input(SseDeserializer deserializer);

  @protected
  ExpenseViewDto sse_decode_expense_view_dto(SseDeserializer deserializer);

  @protected
  FriendBalanceDto sse_decode_friend_balance_dto(SseDeserializer deserializer);

  @protected
  FriendDetailDto sse_decode_friend_detail_dto(SseDeserializer deserializer);

  @protected
  GroupDetailDto sse_decode_group_detail_dto(SseDeserializer deserializer);

  @protected
  GroupSummaryDto sse_decode_group_summary_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActivityEntryDto> sse_decode_list_activity_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceViewDto> sse_decode_list_device_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ExpenseViewDto> sse_decode_list_expense_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FriendBalanceDto> sse_decode_list_friend_balance_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupSummaryDto> sse_decode_list_group_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MemberAmountDto> sse_decode_list_member_amount_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MemberBalanceDto> sse_decode_list_member_balance_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<Payer> sse_decode_list_payer(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SettlementViewDto> sse_decode_list_settlement_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TransferDto> sse_decode_list_transfer_dto(SseDeserializer deserializer);

  @protected
  List<Weight> sse_decode_list_weight(SseDeserializer deserializer);

  @protected
  MemberAmountDto sse_decode_member_amount_dto(SseDeserializer deserializer);

  @protected
  MemberBalanceDto sse_decode_member_balance_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FriendDetailDto? sse_decode_opt_box_autoadd_friend_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupDetailDto? sse_decode_opt_box_autoadd_group_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  OriginalAmountDto? sse_decode_opt_box_autoadd_original_amount_dto(
    SseDeserializer deserializer,
  );

  @protected
  OriginalAmountDto sse_decode_original_amount_dto(
    SseDeserializer deserializer,
  );

  @protected
  Payer sse_decode_payer(SseDeserializer deserializer);

  @protected
  SettlementViewDto sse_decode_settlement_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  SplitPlanDto sse_decode_split_plan_dto(SseDeserializer deserializer);

  @protected
  TransferDto sse_decode_transfer_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Weight sse_decode_weight(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    Engine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_activity_entry_dto(
    ActivityEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_expense_input(
    ExpenseInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_friend_detail_dto(
    FriendDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_detail_dto(
    GroupDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_original_amount_dto(
    OriginalAmountDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_view_dto(DeviceViewDto self, SseSerializer serializer);

  @protected
  void sse_encode_expense_input(ExpenseInput self, SseSerializer serializer);

  @protected
  void sse_encode_expense_view_dto(
    ExpenseViewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_balance_dto(
    FriendBalanceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_detail_dto(
    FriendDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_detail_dto(
    GroupDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_summary_dto(
    GroupSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_activity_entry_dto(
    List<ActivityEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_view_dto(
    List<DeviceViewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_expense_view_dto(
    List<ExpenseViewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend_balance_dto(
    List<FriendBalanceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_summary_dto(
    List<GroupSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_member_amount_dto(
    List<MemberAmountDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_member_balance_dto(
    List<MemberBalanceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_payer(List<Payer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_settlement_view_dto(
    List<SettlementViewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_dto(
    List<TransferDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_weight(List<Weight> self, SseSerializer serializer);

  @protected
  void sse_encode_member_amount_dto(
    MemberAmountDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_member_balance_dto(
    MemberBalanceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_friend_detail_dto(
    FriendDetailDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_group_detail_dto(
    GroupDetailDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_original_amount_dto(
    OriginalAmountDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_original_amount_dto(
    OriginalAmountDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_payer(Payer self, SseSerializer serializer);

  @protected
  void sse_encode_settlement_view_dto(
    SettlementViewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_split_plan_dto(SplitPlanDto self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_dto(TransferDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_weight(Weight self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngine(
    int ptr,
  );
}
